### ISSUE TITLE
db2 client Image build failed

### ISSUE THREAD

**Issue by soydaner** [IBM-i2/analyze-containers#1]
Hello,

db2 client image build process is failing:
First this error appears: 
"The instance "db2inst1" already exists. Specify a new instance name."
then, at the end of process, this final error:
"/bin/sh: /opt/ibm/db2/V11.5/instance/db2iset: No such file or directory"
could you help me to fix it? please
I can share complete error log if you want to see them
P.S. I have no db2 knowledge.

Thank You

**Comment by arianahl** [comment]
Hi @soydaner, can you please give us more information about your system and what you are running?
Please fill the following:

**To Reproduce**
Steps to reproduce the behavior:
1. Run scripts '...'
2. Go to '...'
3. See error

**Hardware and Software information**
 - OS: [e.g. Mac, Windows]
 - Version: [e.g. v2.0.0]
 - i2 Analyze version: [e.g. 4.3.4]
 - Environment type: [e.g. pre-prod, config-dev]
 - Deployment pattern: [e.g. istore, i2c, cstore, i2c_istore, i2c_cstore, schema_dev]

**Comment by soydaner** [comment]
I am following "https://ibm-i2.github.io/analyze-containers/index.html" docs

**To reproduce**:
- Install prerequisites
- Download required tools, software and put them on pre-reqs folder
- cd to scripts folder 
- run: ./createDevEnvironment.sh
- At the image creation phase: the db2 client image creation fails. and process stopped

**Hardware and Software information**
- OS: Linux (Slackware 14.2)
- Version: ?
- i2 Analyze version: 4.3.4
- Environment type: dev environment
- Deployment Pattern: It belongs to 'Creating Config' step and it comes after  "create the configuration development environment" step. Since process failed in env create stage, I did not set the pattern type.

**Comment by arianahl** [comment]
@soydaner thank you for your reply. Unfortunately we currently don't support Linux OS.
Try running the commands in either Windows with Windows Subsystem for Linux or MacOS. For more information, you can read more about it in the [prerequisites](https://ibm-i2.github.io/analyze-containers/content/getting_started.html#prerequisites) section.

**Comment by soydaner** [comment]
Thank you very much. You are right. Since all are containerised, I though that it can run in any OS. Sorry. my mistake!. Now, I run the creation script in Mac OS successfully.

**Comment by arianahl** [comment]
There are many differences between Linux distributions and we use shell tools that have different features so supporting them all is complex. We'll look into it at some point in the future.
Glad it is all working! 

Closing as resolved.
